version: '3.9'

x-wordpress-variables: &wordpress-variables
  WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
  WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
  WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
  WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
  WORDPRESS_CONFIG_EXTRA: |
    define( 'WP_HOME', 'http://${WP_HOME}:${WORDPRESS_PORT}' );
    define( 'WP_SITEURL', 'http://${WP_SITEURL}:${WORDPRESS_PORT}' );
    define( 'FS_METHOD', 'direct' );
    define( 'WP_ENVIRONMENT_TYPE', 'staging' );
    define( 'SCRIPT_DEBUG', true );
    define( 'WP_DISABLE_FATAL_ERROR_HANDLER', true );
    define( 'WP_DEBUG_DISPLAY', true );
    define( 'WP_DEBUG', true );
    define( 'WP_DEBUG_LOG', false );

services:
  wordpress:
    container_name: kineskope_wp
    image: wordpress:${WORDPRESS_VERSION}
    ports:
      - "${WORDPRESS_PORT}:80"
    user: root
    environment: *wordpress-variables
    volumes:
      - ./plugin/:/var/www/html/wp-content/plugins/kineskope/
    depends_on:
      - db
  wp-cli:
    container_name: kineskope_wp-cli
    image: wordpress:cli
    entrypoint: ['/bin/sh']
    user: root
    stdin_open: true
    tty: true
    volumes_from:
      - wordpress
    depends_on:
      - db
    environment: *wordpress-variables
  db:
    container_name: kineskope_db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
  webpack:
    container_name: kineskope_webpack
    working_dir: /app
    image: node:14-slim
    command: bash -c "yarn install --frozen-lockfile && yarn run watch"
    # command: tail -F anything
    volumes:
      - ./:/app
  phpunit:
    container_name: kineskope_phpunit
    image: wordpress:cli-php7.4
    volumes:
      - ./:/app
    command: bash -c "apt-get update && apt-get install -y libxml2-dev && docker-php-ext-install soap && pecl install xdebug && docker-php-ext-enable xdebug && cd /app/ && composer install && vendor/bin/phpunit"

  # svn:
  #   container_name: kineskope_svn
  #   image: wordpress:${WORDPRESS_VERSION}-php7.4-cli
  #   volumes:
  #     - ./plugin:/app
  #   command: bash -c "apt-get update && apt-get install -y subversion && cd /app/ && svn co ${SVN_REPO} ${SVN_CHECKOUT_DIR} && cp -r . ${SVN_CHECKOUT_DIR} && cd ${SVN_CHECKOUT_DIR} && svn add --force * && svn ci -m 'Initial import' --username ${SVN_USERNAME} --password ${SVN_PASSWORD} --non-interactive"
  # svn-publish:
  #   container_name: kineskope_svn-pub
  #   image: wordpress:${WORDPRESS_VERSION}-php7.4-cli
  #   volumes:
  #     - ./plugin:/app
  #   command: bash -c "apt-get update && apt-get install -y subversion && cd ${SVN_CHECKOUT_DIR} && svn up && cp -r /app/* . && svn ci -m 'Update to version ${PLUGIN_VERSION}' --username ${SVN_USERNAME} --password ${SVN_PASSWORD} --non-interactive"

volumes:
  db_data: {}
